### ISSUE TITLE
Cannot run Flutter web WASM with error about identityHashCode

### ISSUE THREAD

**Issue by Rexios80** [leoafarias/pub_api_client#49] opened 2024-05-20 17:18 UTC
This package is surfacing this runtime exception, but I'm not sure it's this package's fault since there are no references to `identityHashCode` in this code base. I'm creating an issue here to see if @leoafarias has any insight to what is going on.

```console
Uncaught (in promise) CompileError: WebAssembly.compileStreaming(): Compiling function #1263:"identityHashCode" failed: type error in return[0] (expected i64, got (ref null 103)) @+1479968
```

https://github.com/flutter/flutter/issues/148617

**Comment by leoafarias** [comment] 2024-05-21 15:02
Will do some research of what could be the problem

**Comment by leoafarias** [comment] 2024-05-21 15:11
@Rexios80 I updated Dart Mappable to see if that could be causing the issue due to how the quality is handled. I have committed on `main`. I'm not sure if this is the problem, but if you can provide a sample code that I can replicate, I can take a further look.

**Comment by Rexios80** [comment] 2024-05-21 15:28
It was a good idea, but unfortunately it didn't change anything

**Comment by Rexios80** [comment] 2024-05-21 15:28
I don't have time to create a minimal sample right now, but this project has the issue: https://github.com/Rexios80/rexios.dev

**Comment by leoafarias** [comment] 2024-05-22 15:26
@Rexios80 It seems this is an issue only happening on Flutter master. I created a reproducible example on the Flutter ticket. I will go ahead and close this for now.

**Closed by leoafarias** 2024-05-22 15:26 UTC
